// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BannersRotationClient is the client API for BannersRotation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannersRotationClient interface {
	AddBanner(ctx context.Context, in *AddBannerBody, opts ...grpc.CallOption) (*Message, error)
}

type bannersRotationClient struct {
	cc grpc.ClientConnInterface
}

func NewBannersRotationClient(cc grpc.ClientConnInterface) BannersRotationClient {
	return &bannersRotationClient{cc}
}

func (c *bannersRotationClient) AddBanner(ctx context.Context, in *AddBannerBody, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/event.BannersRotation/AddBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannersRotationServer is the server API for BannersRotation service.
// All implementations must embed UnimplementedBannersRotationServer
// for forward compatibility
type BannersRotationServer interface {
	AddBanner(context.Context, *AddBannerBody) (*Message, error)
	mustEmbedUnimplementedBannersRotationServer()
}

// UnimplementedBannersRotationServer must be embedded to have forward compatible implementations.
type UnimplementedBannersRotationServer struct {
}

func (UnimplementedBannersRotationServer) AddBanner(context.Context, *AddBannerBody) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBanner not implemented")
}
func (UnimplementedBannersRotationServer) mustEmbedUnimplementedBannersRotationServer() {}

// UnsafeBannersRotationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannersRotationServer will
// result in compilation errors.
type UnsafeBannersRotationServer interface {
	mustEmbedUnimplementedBannersRotationServer()
}

func RegisterBannersRotationServer(s grpc.ServiceRegistrar, srv BannersRotationServer) {
	s.RegisterService(&BannersRotation_ServiceDesc, srv)
}

func _BannersRotation_AddBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBannerBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersRotationServer).AddBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.BannersRotation/AddBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersRotationServer).AddBanner(ctx, req.(*AddBannerBody))
	}
	return interceptor(ctx, in, info, handler)
}

// BannersRotation_ServiceDesc is the grpc.ServiceDesc for BannersRotation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BannersRotation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.BannersRotation",
	HandlerType: (*BannersRotationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBanner",
			Handler:    _BannersRotation_AddBanner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BannersRotation/BannersRotation.proto",
}
